# Generated by Django 5.0.9 on 2025-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0005_alter_embeddingmodel_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingmodel',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'HuggingFace'), ('cohere', 'Cohere'), ('anthropic', 'Anthropic (Claude)')], max_length=20),
        ),
    ]
