# Generated by Django 4.2.7 on 2026-03-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0007_embeddingmodel_external_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='external_guid',
            field=models.CharField(blank=True, help_text='GUID from mg.nexelin.com for LLM model identification in usage stats API', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ModelPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_guid', models.CharField(help_text='GUID from mg.nexelin.com for this model pair (LLM + Embedding) identification in usage stats API', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pair is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding_model', models.ForeignKey(help_text='Embedding model for this pair', on_delete=django.db.models.deletion.CASCADE, related_name='model_pairs', to='EmbeddingModel.embeddingmodel', verbose_name='Embedding Model')),
                ('llm_provider', models.ForeignKey(help_text='LLM model for this pair', on_delete=django.db.models.deletion.CASCADE, related_name='model_pairs', to='EmbeddingModel.llmprovider', verbose_name='LLM Provider')),
            ],
            options={
                'verbose_name': 'Model Pair',
                'verbose_name_plural': 'Model Pairs',
                'ordering': ['llm_provider', 'embedding_model'],
                'indexes': [models.Index(fields=['llm_provider', 'embedding_model'], name='EmbeddingMo_llm_pro_476e2c_idx'), models.Index(fields=['external_guid'], name='EmbeddingMo_externa_66cc37_idx'), models.Index(fields=['is_active'], name='EmbeddingMo_is_acti_ee48ca_idx')],
                'unique_together': {('llm_provider', 'embedding_model')},
            },
        ),
    ]
