# Generated by Django 5.0.9 on 2026-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0008_client_pixel_dashboard_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingmodel',
            name='external_guid',
            field=models.CharField(blank=True, help_text='GUID from MG platform for AI model identification in usage stats API', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='embeddingmodel',
            name='server_type',
            field=models.CharField(blank=True, choices=[('', 'Cloud/API'), ('main', 'Ollama Main Server'), ('light', 'Ollama Light Server')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='API endpoint for Ollama/custom providers (e.g., http://ollama:11434)', null=True),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='external_guid',
            field=models.CharField(blank=True, help_text='GUID from MG platform for LLM model identification in usage stats API', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modelpair',
            name='external_guid',
            field=models.CharField(help_text='GUID from MG platform for this model pair (LLM + Embedding) identification in usage stats API', max_length=255, unique=True),
        ),
    ]
