# Generated by Django 5.0.9 on 2026-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge_platform', '0007_platformlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformlicense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
