# Generated by Django 5.0.9 on 2026-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_clientwhatsappconversation_telegram_chat_id'),
        ('clients', '0039_add_escalation_timeout_fields'),
        ('clients', '0041_add_matrix_hitl_fields'),
    ]

    operations = [
    ]
