# Generated by Django 4.2.7 on 2026-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_lead_and_leads_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeblock',
            name='target_scope',
            field=models.CharField(choices=[('all', 'All (available to everyone)'), ('assistant', 'Assistant only (Oleg)'), ('manager', 'Manager only (Vasya)')], default='all', help_text='Who can access this knowledge block', max_length=20),
        ),
    ]
