# Generated by Django 5.0.9 on 2026-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0062_drop_matrix_hitl_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeconfig',
            name='bot_username',
            field=models.CharField(help_text='Matrix bot user e.g. @facebookbot:matrix.example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='webchat_domain',
            field=models.CharField(blank=True, help_text='Custom base domain for web chat and client portal (e.g. chat.example.com)', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_bridge_matrix_user_id',
            field=models.CharField(blank=True, help_text="Matrix user ID for this client's bridge bot (e.g., @concierge_client_42:jeeves.local)", max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgeblock',
            name='target_scope',
            field=models.CharField(choices=[('all', 'All (available to everyone)'), ('assistant', 'Assistant only (Jeeves)'), ('manager', 'Manager only (Concierge)')], default='all', help_text='Who can access this knowledge block', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappbridgeconfig',
            name='bot_username_template',
            field=models.CharField(default='concierge_client_{client_id}', help_text='Template for Matrix bot usernames per client', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappbridgeconfig',
            name='homeserver_domain',
            field=models.CharField(help_text='Matrix server domain (e.g., matrix.example.com)', max_length=255),
        ),
    ]
