# Generated by Django 5.0.9 on 2026-06-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0063_alter_bridgeconfig_bot_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixRoomBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('source_network', models.CharField(choices=[('matrix', 'Matrix (native)'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('facebook', 'Facebook Messenger')], default='matrix', max_length=20)),
                ('remote_handle', models.CharField(blank=True, help_text='Source-network identifier of the other party (phone, @username, IG handle).', max_length=255)),
                ('last_event_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rooms', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'is_active'], name='clients_mat_client__c817ff_idx'), models.Index(fields=['source_network'], name='clients_mat_source__d0337d_idx')],
            },
        ),
    ]
