homeserver:
    address: http://localhost:8008
    domain: grot.de

appservice:
    address: http://localhost:29321
    hostname: 0.0.0.0
    port: 29321
    id: mautrix-linkedin
    bot:
        username: linkedinbot
        displayname: LinkedIn Bridge Bot
    database:
        type: postgres
        uri: postgres://mautrix:${POSTGRES_MAUTRIX_PASSWORD}@localhost:5433/mautrix_linkedin?sslmode=disable

bridge:
    username_template: linkedin_{{.}}
    permissions:
        "grot.de": user
        "@admin:grot.de": admin
    provisioning:
        prefix: /_matrix/provision
        shared_secret: generate

logging:
    min_level: info
    writers:
        - type: stdout
          format: pretty-colored
