# ============================================
# Matrix Authentication Service for grot.de
# ============================================

http:
  public_base: "https://auth.grot.de/"
  issuer: "https://auth.grot.de/"
  listeners:
    - name: web
      binds:
        - address: "[::]:8080"
      proxy_protocol: false
      resources:
        - name: discovery
        - name: human
        - name: oauth
        - name: compat
        - name: graphql
          playground: false
        - name: assets
    - name: internal
      binds:
        - address: "[::]:8081"
      proxy_protocol: false
      resources:
        - name: health

database:
  uri: "postgres://mas:VJAhKY7vk8soSwfAlUsHMUiCeD7n7gXd@postgres-mas:5432/mas"

passwords:
  enabled: true
  schemes:
    - version: 1
      algorithm: bcrypt
    - version: 2
      algorithm: argon2id
  minimum_complexity: 3

matrix:
  homeserver: "grot.de"
  secret: "kSltGLjJxtXspJZJwNrBksJy4dHABmlbe5VXE9r9cVqpzYnI2Bho0EwlI7KWu2"
  endpoint: "http://synapse:8008"

clients: []

account:
  email_change_allowed: true
  displayname_change_allowed: true
  password_change_allowed: true
  password_recovery_enabled: false

branding:
  service_name: "Grot Chat"

secrets:
  encryption: "d8e86979cf95efbd7545359a605364eea3828e04c284c2f5986685979cd0863e"
  keys:
    - kid: "c58bf29658a86295"
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCjZxPhij7jQqW8
        bPTUJOLr43eTvEBVIqT8HYG/ZDXn/24jKNUBi3TK0LDljxmdjOyr6ESt088BQsny
        DY2nU+Y/cbF3Apq6oJC5AvqbW11LNOVPicqyG0cgw4SoFMQ2WjEWhKw6y4Tv5Dlp
        vFLpUczndqOUSKSfyBU/GJx03HMIhjCpAjI/llUD4WJohmbxOxUogcin4NHhigya
        XF/UHFdNvW4QXjfwqeyAJ5/KMhz3pJe2sE5nkjfMIVWr412iUbZ165Vpm2+erb9f
        0UY1e1ZfOuVpBQ1U1+b/oE87W4pDyCrtiAPZPosZuTo0V39SweS95A14G3jrJaOE
        DnFKypj+ccW+lDg3bJ5vQN7AvbZXd1OSoMPUnMkxMPN11mShLiLqszz76Q5KeB/u
        xGzuyJ5ycvWrNbP8FBS4zEcXznsScEuqA/Cpio43XN7WSikEaj0LfFrphpvFtWKD
        HAYVyy/BtMeq+XhyoRlXPE9Et3KKpABw6rjR7ACy4MPC7erKSlJAac28YD7hjB8/
        kOUywk9AOSMJC43cPalVsVMAtIh0iLPV4gN+j6HKh71mVs/j4RT1Sg9p/tMbA93n
        NQNqoK/VvmCMOrDgroKwiz2r6Ked7pKUb50qLz2OKO9MQBmwwQLvB9xPWSKgk6sK
        psH4IDKf4W9U7hEdkPAbBDMSiz1+lQIDAQABAoICAD9EZuc53tWhdYh6a2VEjvQk
        k6UJC6OrEVRonFcdlt2oAd3tLmQ1udfZa9TGTnW5Hd4FxanES+9CC+0DoGg8TPcd
        r0fUI1LFXqOz6pKCkqHO7kaYpHnHpAekjFWEDOC6lS0R25m8OVGk/THacAPU31Bz
        mCyO3+bZ0pgmkFWTEZsoUejuZ8RFEc+50Z+FApC+fpe7gJS3sKvyBqUxxQzcmFUK
        VnZR9LjjIiYQsYbZVmvwN6nNo93oOGB6O7CdDSEPIGWR/LzyKQq4XVPdNKD6i1u9
        8xtxkFLccZ1iVas261cJRs3Hjy3rUHJ6THX9tte1KTr49NofUPdDEIfOC8GYphmo
        OkvydcWZ3TiQlaYNgqW2JB0JFtzhZEkxdpCizyYdSXYXbHvcpsUWQ8za+JRHHnhZ
        tJJSp1sBl64XmiUYb3kU0zJasox3KDbP6bDcaY+9tLDIkP4RJe+xgs182YZVZ4c9
        1FasgiF8u0ieOge4CSIopXLxW1owFnvGcw6aW2lM9m9uJslrQGBSEeY6LHquW4Vq
        d+3K8NN8mqkYsxufmV5LpAH2FnQ5gBRYrHkPYGAXwPVYXzf/EWmv8r2UGFVFPM9l
        LYfJPMOBCfT8rmN8D81LfhDIEkwnLZHsXOAyDHSL2isszGUT5LmiBxYRCyjoJyrG
        hsesdfEmh1NnXI2fXGL1AoIBAQDT6bIQsQZnKPy413+EVajbU2sVFnB+gG/cjUA2
        Aqbr2TOoYjq51gCtJCLNE2PNxx94BcGS9d0SYCcGtrNYf6r7cOgJYjZai80U1NtR
        5Z9VMjJok8qdu6dajli3Y+3g3XeoHUVTLJSCjc6HgdIwnq8HWlCVHtjicSn4XI4s
        6UWjPiYV+Y+RLxnhu1RFjY8NWcEyX9fxu2KG+ky6NIDqAKjfB+kal7AKnIQLa4+f
        YFZYQYkpY/iQg530Pb7EuBZQHmWDDRtKPrBAO54OgkWnbEYa0+zSEwHg6VJTkYPV
        lojyC/mXs3HPipQ4fTP2Zmn+Flo/Leu5GVBOMm9jPDaz0bRnAoIBAQDFZcR+Q7+E
        cliI6fsqs6D95x9pf3e/j1wh/RWkQkoyeSNV2Q6Nl893qZKnn+3U6QZny3EaplXh
        JGz5uutSApzAfImvXddSD9qEPjtayPJ2TYoKPwxn12IlahK6hKULufbIuQAZPRFP
        hIyTPbbyho53UJGFaJ+ltNLrQosWrcP3IoFoVj4Ui1xB0au2+zf4u4yV7/kHg9w3
        DOxXEga9ec27Ggv44bW43PuUacq7k+r0SjSTeRtkTvn5ra56dus3HRRS9uXuB4EN
        I6aP8njIfNr06aPKV7jPsFJz88FikOPomlWaiVB29k+9quBsU9Pp1ch/PgJR+g40
        8ePbJ/sL7rejAoIBAQCjIe09IjnuokPiu6pjolmp9c6iXjLdf1wdqfM7YNFFEGDP
        CEdzFgZRQ1czDfEv0VEtYSkCTBkSc0i3x1/LCgUDKYjG6H81Nxf6KF5p7l25BTp+
        /P7mbDZJ5PjwvJG8IGFj3pymidQNqMLL2CmJ2i6dd24/TY7iywDnO8ELW8yK/WXu
        Vr6polvHRSF7pZzxRx4N/HBNm9YeWINGePKgsT9O6lUNbqZLlO+lpvjaVRxDNrgz
        T81i2p93DS1VXO14Yd39g9J1VkryN7LWMn0ShKx3LJvLoGw6ywLgaE3X19m2k3dh
        y/caMPEnh2LAFVkVC/oPVvd298C1YegTuZ/Wz+GTAoIBAAmYou7IeF0F+gvd5Bn1
        VZRCUiKc0cN8QqxcU1sC5fyCKxeXT7/Oa4WTts9zVOqO0YLmPv9eqrohPTL+xUXd
        XqV06HSgCUGyB5t6MwR81Fyv9E//NKkvrVPITlTG8gcZ6Udkxv5zG45UEUlvLJ+p
        ru9Z+VkU9v3lRoOtXnmhxO8UvFnIJ4h0Je4FNWXV3Ki45WK8ocydumzqseqhs7Yu
        X7QC1iYpQt5Tz98tLW/lBv0NRnUM5CoCNODQcrT9Zv3s6foGirMBpmJvIz/IN9r3
        RuW1HgNONGvUVI3Sgco65Pl/1z2GA2VlIAdGcVaS1LB/dhnJd+9oSpyETeFvliLE
        XiUCggEBAKFnpnpqun2cVqbcIlK1dmLLnSTJS+CpEwQI3OecAAs8L36nmMo0ug6+
        jeZ7CbNETPufCHbvRUMr21EcO/eoBhTy5Y4woSyvgd1JIRXCT9ltrVNNzu4xLIj3
        k6Ye1kC67fp+fnwZSo5SUlnzKAE0d3GhrlMfgfYGYc7lZxHHV7GeJlP+6ij6vkIY
        38lOaUbuo/pWV8Tr5vRc6crHlNkRFhwGq257+unxTAaWtfepjArtru5QiyD2qw++
        BFeIo+DxssC9sigHTKpjqiBSXQvkXGC9KHJHBzu3pBmIyBoHVtUlVkblEmjrJhmA
        dTgaN5sr7RnPDcXlRlXCDwXAarufqtg=
        -----END PRIVATE KEY-----

telemetry:
  tracing:
    exporter: none
  metrics:
    exporter: none
  sentry:
    dsn: null

