# Generated by Django 4.2.7 on 2026-03-23 09:58

from django.db import migrations, models


def copy_system_prompt(apps, schema_editor):
    AgentConfig = apps.get_model('agents', 'AgentConfig')
    for config in AgentConfig.objects.exclude(system_prompt=''):
        config.consultant_prompt = config.system_prompt
        config.save(update_fields=['consultant_prompt'])


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_create_agent_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='assistant_description',
            field=models.TextField(blank=True, help_text='Description of assistant capabilities (shown in UI + added to prompt)'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='assistant_prompt',
            field=models.TextField(blank=True, help_text='System prompt for Oleg (assistant, Sandbox). Empty = platform default.'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='consultant_description',
            field=models.TextField(blank=True, help_text='Description of consultant capabilities (shown in UI + added to prompt)'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='consultant_prompt',
            field=models.TextField(blank=True, help_text='System prompt for Vasya (consultant, messengers). Empty = platform default.'),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='channel',
            field=models.CharField(choices=[('web', 'Web Chat'), ('telegram', 'Telegram'), ('whatsapp_meta', 'WhatsApp Meta'), ('whatsapp_bridge', 'WhatsApp Bridge'), ('email', 'Email'), ('api', 'API'), ('sandbox', 'Sandbox')], max_length=20),
        ),
        migrations.RunPython(copy_system_prompt, migrations.RunPython.noop),
    ]
