# Generated by Django 5.0.9 on 2026-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_dual_agent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='assistant_prompt',
            field=models.TextField(blank=True, help_text='System prompt for Jeeves (assistant, Sandbox). Empty = platform default.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='consultant_description',
            field=models.TextField(blank=True, help_text='Description of concierge capabilities (shown in UI + added to prompt)'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='consultant_prompt',
            field=models.TextField(blank=True, help_text='System prompt for Concierge (concierge, messengers). Empty = platform default.'),
        ),
    ]
