# Generated by Django 5.0.9 on 2025-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0005_alter_specializationembedding_vector_dim_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specializationdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specializationembedding',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
