# Generated by Django 4.2.7 on 2026-03-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_migrate_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcard',
            name='tagline_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='{"en": "...", "uk": "...", "de": "..."} — overrides tagline per locale'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='target',
            field=models.CharField(choices=[('assistant', 'AI Assistant'), ('manager', 'Client Manager'), ('leads', 'Leads')], default='assistant', max_length=20),
        ),
    ]
