# Generated by Django 4.2.7 on 2026-03-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_lead_and_leads_enabled'),
        ('tools', '0005_seed_tagline_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcard',
            name='skill_scopes',
            field=models.JSONField(blank=True, default=dict, help_text='{"scopes": ["assistant","manager","escalation"], "bidirectional": true}'),
        ),
        migrations.CreateModel(
            name='EdgeMiddleware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Execution order on this edge')),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-edge config overrides for this skill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_middlewares', to='clients.client')),
                ('connection', models.ForeignKey(help_text='The edge this skill is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='middlewares', to='tools.toolconnection')),
                ('skill_card', models.ForeignKey(help_text='The skill acting as middleware', on_delete=django.db.models.deletion.CASCADE, related_name='middleware_usages', to='tools.toolcard')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['client', 'connection'], name='tools_edgem_client__262418_idx')],
                'unique_together': {('connection', 'skill_card')},
            },
        ),
    ]
