# Generated by Django 4.2.7 on 2026-03-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_seed_xlsx_processor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toolconnection',
            unique_together={('client', 'tool_card', 'target')},
        ),
        migrations.AddField(
            model_name='toolcard',
            name='scope_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Available scope options for UI rendering'),
        ),
        migrations.AddField(
            model_name='toolconnection',
            name='scope',
            field=models.JSONField(blank=True, default=dict, help_text='Per-target permissions/scope for this connection'),
        ),
    ]
