# Generated by Django 4.2.7 on 2026-03-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_seed_email_coaching_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcard',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System tool — always connected, cannot be disconnected'),
        ),
    ]
