import {
  EnvelopeSimple,
  BookOpen,
  UsersThree,
  PaperPlaneTilt,
  ChatDots,
  ChatCircle,
  DeviceMobile,
  Globe,
  Robot,
  PlugsConnected,
  Calendar,
  Star,
  Camera,
  Phone,
  Code,
  Lightning,
  Database,
  Shield,
  Bell,
  FileText,
  MagnifyingGlass,
  GearSix,
  Link as LinkIcon,
  Headphones,
  ShoppingCart,
  CreditCard,
  ChartBar,
  ChartPie,
  Tray,
  Hash,
  Wrench,
  TelegramLogo,
  WhatsappLogo,
  FacebookLogo,
  InstagramLogo,
  LinkedinLogo,
  XLogo,
  YoutubeLogo,
  SlackLogo,
  DiscordLogo,
  GoogleLogo,
  MicrosoftOutlookLogo,
} from '@phosphor-icons/react';

// Maps legacy icon slugs (lucide-react names) to Phosphor equivalents.
// Every icon renders in `weight="light"` for the Concierge hairline aesthetic.
const ICON_MAP = {
  mail: EnvelopeSimple,
  'book-open': BookOpen,
  users: UsersThree,
  send: PaperPlaneTilt,
  'message-square': ChatDots,
  'message-circle': ChatCircle,
  smartphone: DeviceMobile,
  globe: Globe,
  bot: Robot,
  plug: PlugsConnected,
  plug2: PlugsConnected,
  calendar: Calendar,
  star: Star,
  camera: Camera,
  phone: Phone,
  code: Code,
  zap: Lightning,
  database: Database,
  shield: Shield,
  bell: Bell,
  'file-text': FileText,
  search: MagnifyingGlass,
  settings: GearSix,
  link: LinkIcon,
  headphones: Headphones,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'bar-chart': ChartBar,
  'pie-chart': ChartPie,
  inbox: Tray,
  hash: Hash,
  wrench: Wrench,
  // Brand logos — Phosphor has them built-in
  telegram: TelegramLogo,
  whatsapp: WhatsappLogo,
  facebook: FacebookLogo,
  instagram: InstagramLogo,
  linkedin: LinkedinLogo,
  twitter: XLogo,
  x: XLogo,
  youtube: YoutubeLogo,
  slack: SlackLogo,
  discord: DiscordLogo,
  google: GoogleLogo,
  outlook: MicrosoftOutlookLogo,
};

const ToolIcon = ({ name, className = '', size = 16 }) => {
  const Icon = ICON_MAP[name];
  if (Icon) return <Icon size={size} weight="light" className={className} />;
  // Small emoji / short string fallback
  if (name && name.length <= 2) {
    return <span className={className} style={{ fontSize: size }}>{name}</span>;
  }
  return <Wrench size={size} weight="light" className={className} />;
};

export default ToolIcon;
