# Generated by Django 4.2.7 on 2026-03-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmbeddingModel', '0008_client_pixel_dashboard_enabled'),
        ('clients', '0049_lead_and_leads_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('translations', models.JSONField(default=dict, help_text='{"en": "Text", "de": "Text"}')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_temperature', models.FloatField(blank=True, null=True)),
                ('default_max_tokens', models.IntegerField(blank=True, null=True)),
                ('default_similarity_threshold', models.FloatField(blank=True, null=True)),
                ('default_max_context_chunks', models.IntegerField(blank=True, null=True)),
                ('default_top_k', models.IntegerField(blank=True, null=True)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('default_language', models.CharField(blank=True, max_length=5)),
                ('language_detection_method', models.CharField(blank=True, choices=[('llm', 'LLM-based'), ('library', 'lingua-py'), ('none', 'Disabled')], max_length=20)),
                ('default_greeting', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmbeddingModel.embeddingmodel')),
                ('default_llm_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmbeddingModel.llmprovider')),
            ],
            options={
                'verbose_name': 'Platform Defaults',
                'verbose_name_plural': 'Platform Defaults',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rollout', models.CharField(choices=[('off', 'Off for everyone'), ('selected', 'Only selected clients'), ('all', 'On for everyone')], default='off', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_clients', models.ManyToManyField(blank=True, to='clients.client')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
