# Generated by Django 5.0.9 on 2025-11-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0005_alter_embeddingmodel_server_type'),
        ('clients', '0025_add_llm_provider_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='embedding_model',
            field=models.ForeignKey(blank=True, help_text='Selected embedding model for this client. If not set, default model will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='EmbeddingModel.embeddingmodel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ClientQRCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name/label for this QR code (e.g., "Front Desk", "Reception", "Table 5")', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of where this QR code is used', verbose_name='Description')),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for customer scanning', null=True, upload_to='clients/qr_codes/', verbose_name='QR Code')),
                ('qr_code_url', models.URLField(blank=True, editable=False, max_length=500, verbose_name='QR Code URL')),
                ('qr_token', models.CharField(editable=False, help_text='Unique token for this QR code used in WhatsApp links', max_length=64, unique=True, verbose_name='QR Token')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QR code is active', verbose_name='Active')),
                ('location', models.CharField(blank=True, help_text='Where this QR code is placed (e.g., "Front Desk", "Table 5", "Reception") or URL for Web Chat', max_length=200, verbose_name='Location')),
                ('integration_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web', 'Web Chat')], default='whatsapp', help_text='Type of integration this QR code is for', max_length=20, verbose_name='Integration Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client QR Code',
                'verbose_name_plural': 'Client QR Codes',
                'ordering': ['client', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientWhatsAppConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(help_text='Customer phone number in format +380671234567', max_length=20, verbose_name='Customer Phone')),
                ('messages', models.JSONField(default=list, help_text='List of messages in JSON format: [{"role": "user|assistant", "content": "...", "timestamp": "..."}]', verbose_name='Messages')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Conversation Start')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Time when conversation ended (null if active)', null=True, verbose_name='Conversation End')),
                ('is_active', models.BooleanField(default=True, help_text='Whether conversation is active (less than 24 hours without messages)', verbose_name='Active')),
                ('total_messages', models.IntegerField(default=0, help_text='Number of messages in conversation', verbose_name='Total Messages')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Session ID')),
                ('language', models.CharField(default='uk', max_length=10, verbose_name='Language')),
                ('context_metadata', models.JSONField(blank=True, default=dict, verbose_name='Context Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='clients.client', verbose_name='Client')),
                ('qr_code', models.ForeignKey(blank=True, help_text='QR code that started this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='clients.clientqrcode', verbose_name='QR Code')),
                ('table', models.ForeignKey(blank=True, help_text='Restaurant table (for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_conversations', to='restaurant.restauranttable', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Client WhatsApp Conversation',
                'verbose_name_plural': 'Client WhatsApp Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description of the knowledge block')),
                ('is_active', models.BooleanField(default=True)),
                ('is_permanent', models.BooleanField(default=False, help_text='Permanent blocks cannot be edited or deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_blocks', to='clients.client')),
            ],
            options={
                'verbose_name': 'Knowledge Block',
                'verbose_name_plural': 'Knowledge Blocks',
                'ordering': ['is_permanent', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='knowledge_block',
            field=models.ForeignKey(blank=True, help_text='Knowledge block this document belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.knowledgeblock'),
        ),
        migrations.CreateModel(
            name='WebParsingRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('website_url', models.URLField(help_text='URL of the website to parse', max_length=500, verbose_name='Website URL')),
                ('description', models.TextField(blank=True, help_text='Description of the parsing request', verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this parsing service (admin only)', max_digits=10, null=True, verbose_name='Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of the parsing request', max_length=20, verbose_name='Status')),
                ('path_to_documents', models.CharField(blank=True, help_text='Server URL and directory path where parsed documents are stored (admin only)', max_length=500, verbose_name='Path to Documents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_parsing_requests', to='clients.client', verbose_name='Client')),
                ('knowledge_block', models.ForeignKey(blank=True, help_text='Knowledge block created from this parsing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsing_requests', to='clients.knowledgeblock', verbose_name='Knowledge Block')),
            ],
            options={
                'verbose_name': 'Web Parsing Request',
                'verbose_name_plural': 'Web Parsing Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientqrcode',
            index=models.Index(fields=['client', 'is_active'], name='clients_cli_client__8d0707_idx'),
        ),
        migrations.AddIndex(
            model_name='clientqrcode',
            index=models.Index(fields=['qr_token'], name='clients_cli_qr_toke_b80f29_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwhatsappconversation',
            index=models.Index(fields=['client', 'customer_phone'], name='clients_cli_client__6a197d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwhatsappconversation',
            index=models.Index(fields=['qr_code'], name='clients_cli_qr_code_796321_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwhatsappconversation',
            index=models.Index(fields=['table'], name='clients_cli_table_i_1dce13_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwhatsappconversation',
            index=models.Index(fields=['started_at'], name='clients_cli_started_efc906_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwhatsappconversation',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_b5fe02_idx'),
        ),
        migrations.AddIndex(
            model_name='clientwhatsappconversation',
            index=models.Index(fields=['session_id', 'created_at'], name='clients_cli_session_74763b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgeblock',
            unique_together={('client', 'name')},
        ),
        migrations.AddIndex(
            model_name='webparsingrequest',
            index=models.Index(fields=['client', 'status'], name='clients_web_client__ff4d37_idx'),
        ),
        migrations.AddIndex(
            model_name='webparsingrequest',
            index=models.Index(fields=['status', 'created_at'], name='clients_web_status_2b41ef_idx'),
        ),
    ]
