# Generated by Django 5.0.9 on 2025-12-01 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0006_alter_embeddingmodel_provider'),
        ('clients', '0031_remove_client_llm_provider_fk_client_webchat_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text='From email address for sending emails', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='email_from_name',
            field=models.CharField(blank=True, help_text='From name for sending emails', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='email_smtp_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMTP email for this client'),
        ),
        migrations.AddField(
            model_name='client',
            name='email_smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='email_smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password or app password', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='email_smtp_port',
            field=models.IntegerField(default=587, help_text='SMTP server port (usually 587 for TLS, 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='client',
            name='email_smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption for SMTP'),
        ),
        migrations.AddField(
            model_name='client',
            name='email_smtp_username',
            field=models.CharField(blank=True, help_text='SMTP username (usually email address)', max_length=255),
        ),
       
        migrations.AddField(
            model_name='client',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Telegram Bot Token from @BotFather', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Enable Telegram Bot for this client'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_webhook_url',
            field=models.URLField(blank=True, help_text='Telegram webhook URL (auto-generated)'),
        ),
        migrations.AddField(
            model_name='client',
            name='widget_enabled',
            field=models.BooleanField(default=False, help_text='Enable web widget for white label clients'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('medical', 'Medical'), ('retail', 'Retail'), ('white_label', 'White Label')], default='generic', help_text='Type of client business for specific features', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text'), ('csv', 'CSV'), ('json', 'JSON'), ('docx', 'Word'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF Image'), ('webp', 'WebP Image')], max_length=10),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('news_type', models.CharField(choices=[('integration', 'Integration'), ('model', 'Model'), ('feature', 'Feature'), ('update', 'Update'), ('announcement', 'Announcement')], default='update', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Image URL from Unsplash or other source', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured news appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_integration', models.CharField(blank=True, help_text='Related integration name', max_length=50)),
                ('related_model', models.CharField(blank=True, help_text='Related model name', max_length=100)),
                ('related_feature', models.CharField(blank=True, help_text='Related feature name', max_length=100)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='clients_new_is_acti_959069_idx'), models.Index(fields=['news_type', '-created_at'], name='clients_new_news_ty_f8ffed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'HR / Recruitment'), ('customer_support', 'Customer Support'), ('legal', 'Legal / Compliance'), ('finance', 'Finance / Analytics'), ('tech', 'Software Development'), ('content', 'Content Creation')], max_length=50)),
                ('industry', models.CharField(choices=[('retail', 'Retail'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('tech', 'Technology'), ('education', 'Education'), ('all', 'All Industries')], default='all', max_length=100)),
                ('description', models.TextField()),
                ('prompt_template', models.TextField(help_text='Prompt template with {{variables}}')),
                ('variables', models.JSONField(default=list, help_text='List of variable definitions')),
                ('examples', models.JSONField(blank=True, default=list, help_text='Example inputs and outputs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(default='gpt-4', help_text='Recommended model', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1500)),
                ('usage_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True, help_text='Public prompts are visible to all users')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured prompts appear first')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='IP address or session ID for anonymous users', max_length=255)),
                ('vote', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='clients.prompt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Vote',
                'verbose_name_plural': 'Prompt Votes',
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['category', 'industry'], name='clients_pro_categor_7a043f_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_public', '-likes_count'], name='clients_pro_is_publ_8f3b46_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_featured', '-created_at'], name='clients_pro_is_feat_3d1b86_idx'),
        ),
        migrations.AddIndex(
            model_name='promptvote',
            index=models.Index(fields=['prompt', 'vote'], name='clients_pro_prompt__8cb1cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promptvote',
            unique_together={('prompt', 'user_identifier')},
        ),
    ]
