# Generated by Django 4.2.7 on 2026-03-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_whatsappbridgeconfig_mautrix_db_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='greeting_message',
            field=models.TextField(blank=True, default='', help_text='Universal greeting message shown to customers on first contact in all channels (web, Telegram, WhatsApp). Displayed exactly as written.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_bridge_matrix_user_id',
            field=models.CharField(blank=True, help_text="Matrix user ID for this client's bridge bot (e.g., @nexelin_client_42:crm.local)", max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappbridgeconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsappbridgeconfig',
            name='provisioning_url',
            field=models.URLField(help_text='mautrix-whatsapp provisioning API URL (e.g., http://mautrix-whatsapp:29318)'),
        ),
    ]
