# Generated by Django 4.2.7 on 2026-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_merge_lead_agent_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientwhatsappconversation',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], db_index=True, default='neutral', max_length=16),
        ),
    ]
