# Generated by Django 4.2.7 on 2026-04-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_merge_20260325_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbridgeconfig',
            name='appservice_as_token',
            field=models.CharField(blank=True, help_text='Appservice AS token from mautrix-whatsapp registration.yaml — used to invite users to bridged rooms', max_length=255),
        ),
    ]
