# Generated by Django 4.2.7 on 2026-04-02 12:22

import MASTER.concierge_platform.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_seed_bridge_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbridgeconnection',
            name='matrix_access_token',
            field=MASTER.concierge_platform.fields.EncryptedTextField(blank=True),
        ),
    ]
