"""Seed data for ToolCards — used by migrations and tests."""

INITIAL_TOOLS = [
    {
        'slug': 'whatsapp-meta',
        'name': 'WhatsApp Business',
        'tagline': 'Дозвольте асистенту відповідати вашим клієнтам у WhatsApp',
        'tagline_i18n': {
            'en': 'Let the assistant reply to your customers on WhatsApp',
            'de': 'Lassen Sie den Assistenten Ihren Kunden auf WhatsApp antworten',
        },
        'icon': 'message-circle',
        'category': 'communication',
        'color': '#25D366',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.whatsapp_meta',
        'auth_type': 'credentials',
        'auth_config': {
            'fields': [
                {'name': 'waba_id', 'label': 'WABA ID', 'required': True},
                {'name': 'app_id', 'label': 'App ID', 'required': True},
                {'name': 'app_secret', 'label': 'App Secret', 'type': 'password', 'required': True},
                {'name': 'access_token', 'label': 'Access Token', 'type': 'password', 'required': True},
                {'name': 'phone_number_id', 'label': 'Phone Number ID', 'required': True},
                {'name': 'phone_number', 'label': 'Phone Number', 'placeholder': '+14155552671'},
                {'name': 'verify_token', 'label': 'Webhook Verify Token', 'required': True},
            ]
        },
        'is_active': False,
    },
    {
        'slug': 'telegram',
        'name': 'Telegram Bot',
        'tagline': 'Підключіть Telegram бота для спілкування з клієнтами',
        'tagline_i18n': {
            'en': 'Connect a Telegram bot to communicate with customers',
            'de': 'Verbinden Sie einen Telegram-Bot zur Kundenkommunikation',
        },
        'icon': 'send',
        'category': 'communication',
        'color': '#0088cc',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.telegram',
        'auth_type': 'api_key',
        'auth_config': {
            'fields': [
                {'name': 'bot_token', 'label': 'Bot Token', 'type': 'password',
                 'placeholder': 'From @BotFather', 'required': True},
            ]
        },
    },
    {
        'slug': 'email-smtp',
        'name': 'Email',
        'tagline': 'Асистент надсилатиме звіти та сповіщення на email',
        'tagline_i18n': {
            'en': 'The assistant will send reports and notifications via email',
            'de': 'Der Assistent sendet Berichte und Benachrichtigungen per E-Mail',
        },
        'icon': 'mail',
        'category': 'communication',
        'color': '#EA4335',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.email_smtp',
        'auth_type': 'credentials',
        'auth_config': {
            'fields': [
                {'name': 'smtp_host', 'label': 'SMTP Host', 'placeholder': 'smtp.gmail.com', 'required': True},
                {'name': 'smtp_port', 'label': 'Port', 'placeholder': '587', 'required': True},
                {'name': 'username', 'label': 'Username', 'required': True},
                {'name': 'password', 'label': 'Password', 'type': 'password', 'required': True},
                {'name': 'from_address', 'label': 'From Email', 'required': True},
                {'name': 'from_name', 'label': 'From Name'},
                {'name': 'use_tls', 'label': 'Use TLS', 'type': 'checkbox', 'default': True},
            ]
        },
    },
    {
        'slug': 'whatsapp-bridge',
        'name': 'WhatsApp Personal',
        'tagline': 'Підключіть особистий WhatsApp через QR-код',
        'tagline_i18n': {
            'en': 'Connect your personal WhatsApp via QR code',
            'de': 'Verbinden Sie Ihr persönliches WhatsApp per QR-Code',
        },
        'icon': 'smartphone',
        'category': 'communication',
        'color': '#128C7E',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.whatsapp_bridge',
        'auth_type': 'qr_code',
        'auth_config': {
            'initiate_url': '/clients/whatsapp/bridge/login/',
            'status_url': '/clients/whatsapp/bridge/login/status/',
        },
    },
    {
        'slug': 'web-widget',
        'name': 'Web Chat',
        'tagline': 'Вбудований чат-віджет для вашого сайту',
        'tagline_i18n': {
            'en': 'Embedded chat widget for your website',
            'de': 'Eingebettetes Chat-Widget für Ihre Website',
        },
        'icon': 'message-square',
        'category': 'communication',
        'color': '#6366f1',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.web_widget',
        'auth_type': 'none',
    },
    {
        'slug': 'hitl-matrix',
        'name': 'Live Manager',
        'tagline': 'Передавайте складні питання живому менеджеру',
        'tagline_i18n': {
            'en': 'Escalate complex questions to a live manager',
            'de': 'Leiten Sie komplexe Fragen an einen Live-Manager weiter',
        },
        'icon': 'users',
        'category': 'communication',
        'color': '#9333ea',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.hitl_matrix',
        'auth_type': 'credentials',
        'auth_config': {
            'fields': [
                {'name': 'manager_user_ids', 'label': 'Matrix Manager IDs', 'type': 'tags',
                 'placeholder': '@manager:matrix.org', 'required': True},
                {'name': 'homeserver_url', 'label': 'Homeserver URL',
                 'placeholder': 'https://matrix.org'},
            ]
        },
    },
    {
        'slug': 'rag-search',
        'name': 'Knowledge Base',
        'tagline': 'База знань — асистент шукає відповіді у ваших документах',
        'tagline_i18n': {
            'en': 'Knowledge base — the assistant searches your documents for answers',
            'de': 'Wissensdatenbank — der Assistent sucht Antworten in Ihren Dokumenten',
        },
        'icon': 'book-open',
        'category': 'ai',
        'color': '#f59e0b',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.rag_search',
        'auth_type': 'none',
        'skill_scopes': {'scopes': ['assistant'], 'bidirectional': False},
    },
    {
        'slug': 'translation',
        'name': 'Auto Translation',
        'tagline': 'Автоматичний переклад повідомлень у обох напрямках',
        'tagline_i18n': {
            'en': 'Automatic message translation in both directions',
            'de': 'Automatische Nachrichtenübersetzung in beide Richtungen',
        },
        'icon': 'languages',
        'category': 'ai',
        'color': '#8b5cf6',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.translation',
        'auth_type': 'none',
        'skill_scopes': {'scopes': ['assistant', 'manager', 'escalation'], 'bidirectional': True},
    },
    {
        'slug': 'xlsx-processor',
        'name': 'XLSX Processor',
        'tagline': 'Створення, редагування та аналіз Excel-файлів',
        'tagline_i18n': {
            'en': 'Create, edit, and analyze Excel spreadsheets',
            'de': 'Excel-Tabellen erstellen, bearbeiten und analysieren',
        },
        'icon': 'file-spreadsheet',
        'category': 'ai',
        'color': '#217346',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.xlsx_processor',
        'auth_type': 'none',
        'skill_scopes': {'scopes': ['assistant', 'manager'], 'bidirectional': True},
    },
    {
        'slug': 'leads',
        'name': 'Lead Management',
        'tagline': 'Збір та управління лідами з усіх каналів',
        'tagline_i18n': {
            'en': 'Lead collection and management across all channels',
            'de': 'Lead-Erfassung und -Verwaltung über alle Kanäle',
        },
        'icon': 'user-plus',
        'category': 'crm',
        'color': '#10b981',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.leads',
        'auth_type': 'none',
        'skill_scopes': {
            'scopes': ['assistant', 'manager'],
            'bidirectional': False,
        },
    },
    {
        'slug': 'sales-intel',
        'name': 'Sales Intelligence',
        'tagline': 'Дослідження компаній: techstack, сайт, дані',
        'tagline_i18n': {
            'en': 'Company research: techstack, website data, company intel',
            'de': 'Unternehmensrecherche: Techstack, Website-Daten, Firmeninformationen',
        },
        'icon': 'search',
        'category': 'crm',
        'color': '#3b82f6',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.sales_intel',
        'auth_type': 'none',
        'skill_scopes': {
            'scopes': ['assistant'],
            'bidirectional': False,
        },
    },
]
