"""Seed data for ToolCards — used by migrations and tests."""

INITIAL_TOOLS = [
    {
        'slug': 'whatsapp-meta',
        'name': 'WhatsApp Business',
        'tagline': 'Дозвольте асистенту відповідати вашим клієнтам у WhatsApp',
        'icon': 'message-circle',
        'category': 'communication',
        'color': '#25D366',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.whatsapp_meta',
        'auth_type': 'credentials',
        'auth_config': {
            'fields': [
                {'name': 'waba_id', 'label': 'WABA ID', 'required': True},
                {'name': 'app_id', 'label': 'App ID', 'required': True},
                {'name': 'app_secret', 'label': 'App Secret', 'type': 'password', 'required': True},
                {'name': 'access_token', 'label': 'Access Token', 'type': 'password', 'required': True},
                {'name': 'phone_number_id', 'label': 'Phone Number ID', 'required': True},
                {'name': 'phone_number', 'label': 'Phone Number', 'placeholder': '+14155552671'},
                {'name': 'verify_token', 'label': 'Webhook Verify Token', 'required': True},
            ]
        },
    },
    {
        'slug': 'telegram',
        'name': 'Telegram Bot',
        'tagline': 'Підключіть Telegram бота для спілкування з клієнтами',
        'icon': 'send',
        'category': 'communication',
        'color': '#0088cc',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.telegram',
        'auth_type': 'api_key',
        'auth_config': {
            'fields': [
                {'name': 'bot_token', 'label': 'Bot Token', 'type': 'password',
                 'placeholder': 'From @BotFather', 'required': True},
            ]
        },
    },
    {
        'slug': 'email-smtp',
        'name': 'Email',
        'tagline': 'Асистент надсилатиме звіти та сповіщення на email',
        'icon': 'mail',
        'category': 'communication',
        'color': '#EA4335',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.email_smtp',
        'auth_type': 'credentials',
        'auth_config': {
            'fields': [
                {'name': 'smtp_host', 'label': 'SMTP Host', 'placeholder': 'smtp.gmail.com', 'required': True},
                {'name': 'smtp_port', 'label': 'Port', 'placeholder': '587', 'required': True},
                {'name': 'username', 'label': 'Username', 'required': True},
                {'name': 'password', 'label': 'Password', 'type': 'password', 'required': True},
                {'name': 'from_address', 'label': 'From Email', 'required': True},
                {'name': 'from_name', 'label': 'From Name'},
                {'name': 'use_tls', 'label': 'Use TLS', 'type': 'checkbox', 'default': True},
            ]
        },
    },
    {
        'slug': 'whatsapp-bridge',
        'name': 'WhatsApp Personal',
        'tagline': 'Підключіть особистий WhatsApp через QR-код',
        'icon': 'smartphone',
        'category': 'communication',
        'color': '#128C7E',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.whatsapp_bridge',
        'auth_type': 'qr_code',
        'auth_config': {'initiate_url': '/api/tools/whatsapp-bridge/qr/'},
    },
    {
        'slug': 'web-widget',
        'name': 'Web Chat',
        'tagline': 'Вбудований чат-віджет для вашого сайту',
        'icon': 'message-square',
        'category': 'communication',
        'color': '#6366f1',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.web_widget',
        'auth_type': 'none',
    },
    {
        'slug': 'hitl-matrix',
        'name': 'Live Manager',
        'tagline': 'Передавайте складні питання живому менеджеру',
        'icon': 'users',
        'category': 'communication',
        'color': '#9333ea',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.hitl_matrix',
        'auth_type': 'credentials',
        'auth_config': {
            'fields': [
                {'name': 'manager_user_ids', 'label': 'Matrix Manager IDs', 'type': 'tags',
                 'placeholder': '@manager:matrix.org', 'required': True},
                {'name': 'homeserver_url', 'label': 'Homeserver URL',
                 'placeholder': 'https://matrix.org'},
            ]
        },
    },
    {
        'slug': 'rag-search',
        'name': 'Knowledge Base',
        'tagline': 'База знань — асистент шукає відповіді у ваших документах',
        'icon': 'book-open',
        'category': 'ai',
        'color': '#f59e0b',
        'transport_type': 'builtin',
        'is_builtin': True,
        'builtin_handler': 'mcp_hub.builtin.rag_search',
        'auth_type': 'none',
    },
]
