homeserver:
    address: http://localhost:8008
    domain: grot.de

appservice:
    address: http://localhost:29320
    hostname: 0.0.0.0
    port: 29320
    id: mautrix-meta-instagram
    bot:
        username: instagrambot
        displayname: Instagram Bridge Bot
    database:
        type: postgres
        uri: postgres://mautrix:${POSTGRES_MAUTRIX_PASSWORD}@localhost:5433/mautrix_meta_instagram?sslmode=disable

meta:
    mode: instagram

bridge:
    username_template: instagram_{{.}}
    permissions:
        "grot.de": user
        "@admin:grot.de": admin
    provisioning:
        prefix: /_matrix/provision
        shared_secret: generate

logging:
    min_level: info
    writers:
        - type: stdout
          format: pretty-colored
