# Generated by Django 5.0.9 on 2025-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0004_llmprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingmodel',
            name='server_type',
            field=models.CharField(blank=True, choices=[('', 'Cloud/API'), ('main', 'Main Server (192.168.0.51)'), ('light', 'Light Server (192.168.0.52)')], default='', max_length=20),
        ),
    ]
