# Generated by Django 5.0.9 on 2025-11-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_add_llm_provider_fk'),
    ]

    operations = [
    ]
