# Generated by Django 5.0.9 on 2025-11-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_sync_state'),
    ]

    operations = [
    ]
