# Generated by Django 5.0.9 on 2025-11-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_remove_client_llm_provider_fk_client_embedding_model_and_more'),
        ('clients', '0028_webparsingrequest'),
    ]

    operations = [
    ]
