# Generated by Django 5.0.9 on 2025-11-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_merge_20251118_1446'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webparsingrequest',
            new_name='clients_web_client__ff4d37_idx',
            old_name='clients_web_client__idx',
        ),
        migrations.RenameIndex(
            model_name='webparsingrequest',
            new_name='clients_web_status_2b41ef_idx',
            old_name='clients_web_status__idx',
        ),
    ]
