# Generated by Django 5.0.9 on 2025-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_rename_clients_web_client__idx_clients_web_client__ff4d37_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='webchat_domain',
            field=models.CharField(blank=True, help_text='Custom base domain for web chat and client portal (e.g. ai.bytekraft.net)', max_length=255),
        ),
    ]
