# Generated by Django 4.2.7 on 2026-03-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmbeddingModel', '0008_client_pixel_dashboard_enabled'),
        ('clients', '0043_alter_conversation_language_default_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(help_text='Domain of the website (example.com)', max_length=255, verbose_name='Site')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Page URL')),
                ('emails', models.JSONField(blank=True, default=list, help_text='List of unique emails found on the page/site')),
                ('phones', models.JSONField(blank=True, default=list, help_text='List of unique phone numbers')),
                ('addresses', models.JSONField(blank=True, default=list, help_text='List of detected postal addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Extension Entity',
                'verbose_name_plural': 'Extension Entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Exact URL of the page where the extension was used', max_length=1000, verbose_name='Page URL')),
                ('site_name', models.CharField(help_text='Domain of the website (example.com)', max_length=255, verbose_name='Site')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Page title')),
                ('headings', models.JSONField(blank=True, default=list, help_text='List of headings with levels and text')),
                ('lists', models.JSONField(blank=True, default=list, help_text='Lists (ul/ol) with items')),
                ('tables', models.JSONField(blank=True, default=list, help_text='Tables with header/rows')),
                ('quotes', models.JSONField(blank=True, default=list, help_text='Quotes / highlighted text blocks')),
                ('full_text', models.TextField(blank=True, help_text='Raw visible text content of the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Extension Page',
                'verbose_name_plural': 'Extension Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='clientcustomprompt',
            new_name='clients_cli_client__aa61f5_idx',
            old_name='clients_cli_client__idx',
        ),
        migrations.RenameIndex(
            model_name='clientcustomprompt',
            new_name='clients_cli_client__e1769d_idx',
            old_name='clients_cli_client__order_idx',
        ),
        migrations.RenameIndex(
            model_name='clientwhatsappconversation',
            new_name='clients_cli_telegra_e237b1_idx',
            old_name='clients_cli_telegram_chat_id_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='llm_provider_fk',
        ),
        migrations.AddField(
            model_name='client',
            name='dashboard_custom_style',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Custom dashboard styling for white label clients. Example:\n        {\n            "primary_color": "#4F46E5",\n            "secondary_color": "#10B981",\n            "logo_url": "https://example.com/logo.png",\n            "background_gradient": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",\n            "custom_css": ".dashboard-card { border-radius: 16px; }"\n        }\n        '),
        ),
        migrations.AddField(
            model_name='client',
            name='dashboard_custom_widgets',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Custom dashboard widgets configuration. Example:\n        {\n            "widgets": [\n                {\n                    "type": "html_block",\n                    "title": "Welcome",\n                    "content": "<h3>Welcome!</h3>",\n                    "order": 1,\n                    "enabled": true\n                },\n                {\n                    "type": "iframe",\n                    "title": "Analytics",\n                    "url": "https://example.com/embed",\n                    "height": 400,\n                    "order": 2,\n                    "enabled": true\n                }\n            ]\n        }\n        Supported types: html_block, markdown_block, iframe, video, image_banner, quick_links, announcement\n        '),
        ),
        migrations.AddField(
            model_name='client',
            name='dashboard_layout',
            field=models.CharField(choices=[('default', 'Default (Stats + InfoCenter + TopPrompts)'), ('minimal', 'Minimal (Stats only)'), ('white_label', 'White Label (Custom widgets only)'), ('hybrid', 'Hybrid (Standard + Custom widgets)')], default='default', help_text='Dashboard layout type for this client', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='dashboard_show_info_center',
            field=models.BooleanField(default=True, help_text='Show Info Center widget in client dashboard'),
        ),
        migrations.AddField(
            model_name='client',
            name='dashboard_show_top_prompts',
            field=models.BooleanField(default=True, help_text='Show Top Prompts widget in client dashboard'),
        ),
        migrations.AddField(
            model_name='client',
            name='extension_enabled',
            field=models.BooleanField(default=False, help_text='Enable Google Chrome extension for web scraping & semantic analysis'),
        ),
        migrations.AddField(
            model_name='client',
            name='llm_provider_model',
            field=models.ForeignKey(blank=True, help_text='Selected LLM provider model. If not set, llm_provider and llm_model_name will be used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='EmbeddingModel.llmprovider'),
        ),
        migrations.AddField(
            model_name='client',
            name='pixel_dashboard_enabled',
            field=models.BooleanField(default=False, help_text='Enable pixel art dashboard visualization for this client'),
        ),
        migrations.AddField(
            model_name='client',
            name='sync_usage_stats',
            field=models.BooleanField(default=True, help_text='Enable/disable sending usage statistics to MG for this client'),
        ),
        migrations.AddField(
            model_name='clientwhatsappconversation',
            name='forced_language',
            field=models.CharField(blank=True, default='', help_text='Explicitly requested language (persists until user requests a change)', max_length=10, verbose_name='Forced Language'),
        ),
        migrations.AddField(
            model_name='clientwhatsappconversation',
            name='last_user_language',
            field=models.CharField(blank=True, default='', help_text='Language detected from the most recent user message', max_length=10, verbose_name='Last User Language'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file for this news item', null=True, upload_to='news/images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations for title and description in all supported languages (en, de, es, fr, it, nl, da)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='custom_system_prompt',
            field=models.TextField(blank=True, help_text="Custom system prompt for this client's AI assistant. Leave empty to use default. Note: Use custom_prompts for multiple prompts management."),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_report_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic email reports for closed chat sessions'),
        ),
        migrations.AlterField(
            model_name='clientcustomprompt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(help_text='Description in English (default language)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL from Unsplash or other source (used if image file is not uploaded)', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Title in English (default language)', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='clientwhatsappconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False), models.Q(('session_id', ''), _negated=True)), fields=('client', 'session_id'), name='unique_client_session'),
        ),
        migrations.AddField(
            model_name='extensionpage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_pages', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='extensionpage',
            name='knowledge_block',
            field=models.ForeignKey(blank=True, help_text='Per-site knowledge block created for extension content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_pages', to='clients.knowledgeblock'),
        ),
        migrations.AddField(
            model_name='extensionentity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_entities', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='extensionentity',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='clients.extensionpage', verbose_name='Extension Page'),
        ),
        migrations.AddIndex(
            model_name='extensionpage',
            index=models.Index(fields=['client', 'site_name'], name='clients_ext_client__0c142d_idx'),
        ),
        migrations.AddIndex(
            model_name='extensionpage',
            index=models.Index(fields=['client', 'url'], name='clients_ext_client__a78720_idx'),
        ),
        migrations.AddIndex(
            model_name='extensionentity',
            index=models.Index(fields=['client', 'site_name'], name='clients_ext_client__45bb43_idx'),
        ),
    ]
