# Generated by Django 4.2.7 on 2026-03-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_client_pixel_dashboard_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephony_enabled',
            field=models.BooleanField(default=False, help_text='Enable telephony/voice AI for this client'),
        ),
        migrations.CreateModel(
            name='ClientTelephonyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('voice_config', models.JSONField(blank=True, default=dict, help_text='{"model": "alloy", "speed": 1.0, "language": "en-US"}')),
                ('response_config', models.JSONField(blank=True, default=dict, help_text='{"mode": "prompt_only", "system_prompt": "...", "max_response_tokens": 150, "temperature": 0.3, "rag_enabled": false, "rag_max_chunks": 2}')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephony_config', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Telephony Config',
                'verbose_name_plural': 'Client Telephony Configs',
            },
        ),
    ]
