# Generated by Django 4.2.7 on 2026-03-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_client_greeting_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='leads_enabled',
            field=models.BooleanField(default=False, help_text='Enable lead collection from messenger conversations. LLM will extract contact data and interest score.'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('request_summary', models.TextField(blank=True, default='')),
                ('interest_score', models.IntegerField(default=3, help_text='Interest level 1-5, determined by LLM based on conversation context')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web Chat'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clients.client')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.clientwhatsappconversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='clients_lea_client__5fcbf7_idx'), models.Index(fields=['client', 'status'], name='clients_lea_client__9a5caf_idx')],
            },
        ),
    ]
