# Generated by Django 4.2.7 on 2026-03-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_dual_agent_fields'),
        ('clients', '0050_add_target_scope_to_knowledge_block'),
    ]

    operations = [
        # RemoveField llm_provider_fk removed — already dropped in 0032
        migrations.AddField(
            model_name='lead',
            name='agent_session',
            field=models.ForeignKey(blank=True, help_text='MCP pipeline session that generated this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='agents.agentsession'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('web', 'Web Chat'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='web', max_length=20),
        ),
    ]
