# Generated by Django 4.2.7 on 2026-04-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_add_appservice_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='llm_provider_fk',
        ),
        migrations.CreateModel(
            name='ChannelAutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp_bridge', 'WhatsApp'), ('telegram', 'Telegram'), ('meta_instagram', 'Instagram'), ('meta_messenger', 'Facebook Messenger'), ('linkedin', 'LinkedIn'), ('imessage', 'iMessage')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_mode', models.CharField(choices=[('always', 'Always (24/7)'), ('scheduled', 'Scheduled hours')], default='always', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('schedule', models.JSONField(blank=True, default=list, help_text='Weekly schedule: [{"day": 0, "start": "09:00", "end": "18:00", "enabled": true}, ...]')),
                ('contact_mode', models.CharField(choices=[('all', 'Respond to all'), ('all_except', 'Respond to all except listed'), ('only', 'Respond only to listed')], default='all', max_length=15)),
                ('contact_list', models.JSONField(blank=True, default=list, help_text='List of contact identifiers: ["48571079588", ...]')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_auto_replies', to='clients.client')),
            ],
        ),
        migrations.AddConstraint(
            model_name='channelautoreply',
            constraint=models.UniqueConstraint(fields=('client', 'channel'), name='unique_client_channel'),
        ),
    ]
