# Generated by Django 4.2.7 on 2026-04-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_channelauto_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('meta-facebook', 'Facebook Messenger'), ('meta-instagram', 'Instagram DM'), ('linkedin', 'LinkedIn Messages')], max_length=30, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('provisioning_url', models.URLField(help_text='mautrix provisioning API base URL')),
                ('provisioning_secret', models.CharField(max_length=255)),
                ('bot_username', models.CharField(help_text='Matrix bot user e.g. @facebookbot:grot.de', max_length=255)),
                ('auth_flow', models.CharField(choices=[('qr_code', 'QR Code'), ('cookies', 'Browser Cookies')], max_length=20)),
                ('default_scopes', models.JSONField(default=list, help_text='Default targets')),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('popup_url', models.URLField(blank=True, help_text='Login URL for cookie auth')),
                ('cookie_domains', models.JSONField(default=list)),
                ('required_cookies', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Bridge Config',
            },
        ),
        migrations.CreateModel(
            name='ClientBridgeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_user_id', models.CharField(blank=True, max_length=255)),
                ('matrix_access_token', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('pending', 'Pending'), ('connected', 'Connected'), ('expired', 'Expired'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('remote_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('login_process_id', models.CharField(blank=True, max_length=255)),
                ('login_step_id', models.CharField(blank=True, max_length=255)),
                ('login_flow_id', models.CharField(blank=True, max_length=255)),
                ('bridge_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='clients.bridgeconfig')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_connections', to='clients.client')),
            ],
            options={
                'unique_together': {('client', 'bridge_config')},
            },
        ),
    ]
