# Generated by Django 4.2.7 on 2026-03-19 13:04

import MASTER.nexelin_platform.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0049_lead_and_leads_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('productivity', 'Productivity'), ('analytics', 'Analytics'), ('ai', 'AI & Knowledge'), ('crm', 'CRM & Sales'), ('custom', 'Custom')], max_length=20)),
                ('mcp_server_url', models.CharField(blank=True, max_length=500)),
                ('transport_type', models.CharField(choices=[('builtin', 'Built-in Django handler'), ('sse', 'SSE (Server-Sent Events)'), ('streamable_http', 'Streamable HTTP')], max_length=20)),
                ('is_builtin', models.BooleanField(default=False)),
                ('builtin_handler', models.CharField(blank=True, max_length=200)),
                ('tools_schema', models.JSONField(blank=True, default=list)),
                ('auth_type', models.CharField(choices=[('none', 'No auth required'), ('oauth2', 'OAuth 2.0'), ('api_key', 'API Key'), ('credentials', 'Custom credentials form'), ('qr_code', 'QR Code scan')], max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToolConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending setup'), ('connected', 'Connected'), ('error', 'Error'), ('disconnected', 'Disconnected'), ('expired', 'Token expired')], default='pending', max_length=20)),
                ('credentials', MASTER.nexelin_platform.fields.EncryptedJSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_connections', to='clients.client')),
                ('tool_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tools.toolcard')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'status'], name='tools_toolc_client__b78a17_idx'), models.Index(fields=['tool_card', 'status'], name='tools_toolc_tool_ca_377153_idx')],
                'unique_together': {('client', 'tool_card')},
            },
        ),
    ]
