# Generated by Django 4.2.7 on 2026-03-20 07:42

from django.db import migrations


def populate_tagline_i18n(apps, schema_editor):
    """Copy tagline_i18n from seed_data into existing ToolCards."""
    from Jeeves.tools.seed_data import INITIAL_TOOLS

    ToolCard = apps.get_model('tools', 'ToolCard')
    i18n_map = {t['slug']: t.get('tagline_i18n', {}) for t in INITIAL_TOOLS}

    for card in ToolCard.objects.filter(slug__in=i18n_map.keys()):
        i18n = i18n_map.get(card.slug, {})
        if i18n and card.tagline_i18n != i18n:
            card.tagline_i18n = i18n
            card.save(update_fields=['tagline_i18n'])


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_add_target_position_tagline_i18n'),
    ]

    operations = [
        migrations.RunPython(populate_tagline_i18n, migrations.RunPython.noop),
    ]
