# Generated by Django 5.0.9 on 2026-04-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_seed_builtin_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolcard',
            name='transport_type',
            field=models.CharField(choices=[('builtin', 'Built-in Django handler'), ('sse', 'SSE (Server-Sent Events)'), ('streamable_http', 'Streamable HTTP'), ('stdio', 'Stdio (local subprocess)')], max_length=20),
        ),
        migrations.CreateModel(
            name='InstalledMCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('package_type', models.CharField(choices=[('npm', 'npm'), ('pypi', 'PyPI')], max_length=10)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('run_command', models.CharField(max_length=500)),
                ('run_args', models.JSONField(blank=True, default=list)),
                ('env_config', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('failed', 'Failed'), ('removed', 'Removed')], default='installed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('tool_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installed_server', to='tools.toolcard')),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
    ]
