# Generated by Django 4.2.7 on 2026-03-19 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0049_lead_and_leads_enabled'),
        ('tools', '0003_migrate_connections'),
        ('EmbeddingModel', '0008_client_pixel_dashboard_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(blank=True)),
                ('greeting_message', models.TextField(blank=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('similarity_threshold', models.FloatField(blank=True, null=True)),
                ('max_context_chunks', models.IntegerField(blank=True, null=True)),
                ('top_k', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=5)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('language_detection', models.BooleanField(blank=True, null=True)),
                ('escalation_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='clients.client')),
                ('embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmbeddingModel.embeddingmodel')),
                ('llm_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmbeddingModel.llmprovider')),
            ],
            options={
                'verbose_name': 'Agent Config',
                'verbose_name_plural': 'Agent Configs',
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('web', 'Web Chat'), ('telegram', 'Telegram'), ('whatsapp_meta', 'WhatsApp Meta'), ('whatsapp_bridge', 'WhatsApp Bridge'), ('email', 'Email'), ('api', 'API')], max_length=20)),
                ('external_user_id', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agents.agentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('llm', 'LLM Generation'), ('tool', 'MCP Tool Call'), ('rag', 'RAG Search'), ('escalation', 'HITL Escalation')], max_length=20)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.IntegerField(null=True)),
                ('tokens_used', models.IntegerField(null=True)),
                ('cost', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.agentsession')),
                ('tool_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolconnection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='agents_agen_session_4f6e69_idx'), models.Index(fields=['call_type', 'status'], name='agents_agen_call_ty_e37507_idx'), models.Index(fields=['tool_connection', 'created_at'], name='agents_agen_tool_co_d23d8d_idx')],
            },
        ),
    ]
